---
title: "GSE263932 scRNA-seq SLE"
output: html_notebook
---

 
```{r}
library(Seurat)
library(ggplot2)
library(dplyr)
```


```{r}
path <- "~/projects/2024/RA/GSE263932/"
setwd(path)
set.seed(2024)
# f_barcodes <- dir(pattern = "*barcodes.tsv.gz")
# # f_features <- character()
# # f_matrix <- character()
# d_name <- character()
# for (i in 1:length(f_barcodes)) {
#   # f_features[i] <- paste0(substr(f_barcodes[i], 1, (nchar(f_barcodes[i])-15)),"features.tsv.gz")
#   # f_matrix[i] <- paste0(substr(f_barcodes[i], 1, (nchar(f_barcodes[i])-15)),"matrix.mtx.gz")
#   d_name[i] <- substr(f_barcodes[i], 1, 10)
#   # if (!file.exists(paste0(path,d_name[i],"/barcodes.tsv.gz"))) {
#   #   dir.create(paste0(path,d_name[i]))
#   #   file.copy(paste0(path,f_barcodes[i]), paste0(path,d_name[i],"/barcodes.tsv.gz"))
#   #   file.copy(paste0(path,f_features[i]), paste0(path,d_name[i],"/features.tsv.gz"))
#   #   file.copy(paste0(path,f_matrix[i]), paste0(path,d_name[i],"/matrix.mtx.gz"))
#   # }
# }
```

```{r}
# scdata <- list()
# for (i in 1:length(f_barcodes)) {
#   data <- Read10X(data.dir = paste0(path,d_name[i]))
#   scdata[[i]] <- CreateSeuratObject(counts = data, project = d_name[i])
# }
# print(scdata)
```

```{r}
# GSE263932 <- merge(scdata[[1]], y = scdata[-1], add.cell.ids = d_name)
```

```{r}
# GSE263932
```

```{r}
# rm(data,scdata,a,f_barcodes,f_features,f_matrix,i)
# gc()
```


# QC
```{r}
# GSE263932[["percent.mt"]] <- PercentageFeatureSet(GSE263932, pattern = "^MT-")
# GSE263932[["percent.ribo"]] <- PercentageFeatureSet(GSE263932, pattern = "^RPS|^RPL")
# GSE263932[["percent.hb"]] <- PercentageFeatureSet(GSE263932, pattern = "^HB[^(P)]")
```


```{r, fig.width= 12, fig.height= 6}
# VlnPlot(GSE263932, features = c("nFeature_RNA", "nCount_RNA", "percent.mt", "percent.ribo", "percent.hb" ), ncol = 5, pt.size = 0)
# VlnPlot(GSE263932, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3, pt.size = 0)
```

```{r, fig.width= 12, fig.height= 6}
# plot1 <- FeatureScatter(GSE263932, feature1 = "nCount_RNA", feature2 = "percent.mt", raster = F)
# plot2 <- FeatureScatter(GSE263932, feature1 = "nCount_RNA", feature2 = "nFeature_RNA", raster = F)
# plot1 + plot2
```



```{r}
path <- "~/projects/2024/RA/GSE263932/"
if (!file.exists(paste0(path,"GSE263932.rds"))) {
  saveRDS(GSE263932, file = paste0(path,"GSE263932.rds"))
}
if (!exists("GSE263932")) {
  GSE263932 <- readRDS(paste0(path,"GSE263932.rds"))
}
GSE263932<- JoinLayers(GSE263932)
```

```{r}
dim(GSE263932)
LSP1_gene <- c("CEBPA", "CEBPB", "IL1B", "CCL3", "TNF", "CCL4", "CCL5", "SPP1", "CD7", "MSR1", "ITGAM", "KIT", "CD14", "CSF3R", "IL1R2", "CSF1R", "ITGA1", "ITGA5", "ITGB5", "ITGB1", "CAMP", "THBS1", "C3", "MEFV", "FOS", "CYBB", "CARD9", "IRF7", "OAS3", "NLRP3", "CTSB", "IKBKE", "MPO")
LSP1_gene[!is.element(LSP1_gene,rownames(GSE263932))]
```

```{r}
counts <- GSE263932@assays$RNA@layers$counts
gene_count <- rowSums(counts >0)
genes_to_keep <- names(gene_count[gene_count >=10])
# dim(GSE263932)
# LSP1_gene[!is.element(LSP1_gene,rownames(GSE263932))]
# LSP1_gene_sub <- LSP1_gene[is.element(LSP1_gene,rownames(GSE263932))]
# Cell_count <- cbind(rowSums(counts[LSP1_gene,]>0),rowSums(counts[LSP1_gene,]))
```

```{r}
GSE263932 <- subset(GSE263932, features = genes_to_keep)
dim(GSE263932)
GSE263932 <- subset(GSE263932, subset = nFeature_RNA > 200 & nFeature_RNA < 5000 & percent.mt < 20)
dim(GSE263932)
LSP1_gene[!is.element(LSP1_gene,rownames(GSE263932))]
LSP1_gene_sub <- LSP1_gene[is.element(LSP1_gene,rownames(GSE263932))]
# Cell_count <- cbind(rowSums(counts[LSP1_gene,]>0),rowSums(counts[LSP1_gene,]))
rm(counts, genes_to_keep)
gc()
# write.csv(Cell_count, file = paste0(path,"GSE263932_cell_count_011325.csv"))
```


```{r, fig.width= 12, fig.height= 6}
# VlnPlot(GSE263932, features = c("nFeature_RNA", "nCount_RNA", "percent.mt", "percent.ribo", "percent.hb" ), ncol = 5, pt.size = 0)
VlnPlot(GSE263932, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3, pt.size = 0)
```

```{r, fig.width= 12, fig.height= 6}
plot1 <- FeatureScatter(GSE263932, feature1 = "nCount_RNA", feature2 = "percent.mt", raster = F)
plot2 <- FeatureScatter(GSE263932, feature1 = "nCount_RNA", feature2 = "nFeature_RNA", raster = F)
plot1 + plot2
```

```{r}
GSE263932 <- NormalizeData(GSE263932, normalization.method = "LogNormalize", scale.factor = 10000)
```

```{r}
GSE263932 <- FindVariableFeatures(GSE263932, selection.method = "vst", nfeatures = 2000)
```



```{r}
GSE263932 <- ScaleData(GSE263932, features = rownames(GSE263932))
set.seed(2024)
GSE263932 <- RunPCA(GSE263932, verbose = F)
```

```{r}
ElbowPlot(GSE263932)
```


```{r}
DimPlot(GSE263932, reduction = "pca", raster = F)
```

```{r}
set.seed(2024)
GSE263932 <- RunUMAP(GSE263932, dims = 1:11)
GSE263932 <- FindNeighbors(GSE263932, dims = 1:11)
GSE263932 <- FindClusters(GSE263932, resolution = 1)
```

```{r}
DimPlot(GSE263932)
DimPlot(GSE263932, group.by = "orig.ident")
```

```{r}
Idents(GSE263932) <- GSE263932$orig.ident
GSE263932 <- RenameIdents(GSE263932, "GSM8207627" = "pre", "GSM8207628" = "post", "GSM8207629" = "pre", "GSM8207630" = "post", "GSM8207631" = "pre", "GSM8207632" = "post", "GSM8207633" = "pre", "GSM8207634" = "post", "GSM8207635" = "pre", "GSM8207636" = "post")
GSE263932$pre_post <- Idents(GSE263932)
```

```{r}
DimPlot(GSE263932, reduction = "umap", raster = F, group.by = "pre_post")
```

# Harmony
```{r}
library(harmony)
set.seed(2024)
options(repr.plot.height = 2.5, repr.plot.width = 6)
GSE263932 <- RunHarmony(GSE263932,"orig.ident", plot_convergence = T)
```

```{r}
harmony_embeddings <- Embeddings(GSE263932, "harmony")
harmony_embeddings[1:5, 1:5]
DimPlot(GSE263932, reduction = "harmony", group.by = "orig.ident",raster = F)
```

```{r}
set.seed(2024)
GSE263932 <- RunUMAP(GSE263932, dims = 1:11, reduction = "harmony")
GSE263932 <- FindNeighbors(GSE263932, dims = 1:11)
GSE263932 <- FindClusters(GSE263932, resolution = 1)
```


```{r}
DimPlot(GSE263932, raster = F, reduction = "umap")
DimPlot(GSE263932, group.by = "orig.ident", reduction = "umap")
```

```{r}
DimPlot(GSE263932, reduction = "umap", raster = F, group.by = "pre_post")
```

```{r}
# mm <- c("CD2", "CD3", "CD14", "CD16", "CD36", "CD43", "CD56", "CD66b", "GlyA")
mm <- c("CD2", "CD3D", "CD3E", "CD3G", "CD247", "CD14", "FCGR3A", "FCGR3B", "CD36", "SPN", "NCAM1", "CEACAM8", "GYPA")

mm <- mm[is.element(mm,rownames(GSE263932))]
```

```{r, fig.width= 12, fig.height= 12}
FeaturePlot(GSE263932, features = mm, ncol = 3, raster = F)
```

```{r, fig.width= 12, fig.height= 12}
FeaturePlot(GSE263932, features = mm, ncol = 3, raster = F)
```



```{r}
b_cells <- read_excel("~/projects/2024/RA/GSE263932/b_cells_remains_012825.xlsx")
B_GSE263932 <- subset(GSE263932, cells = b_cells$barcodes)
```

```{r}
DimPlot(B_GSE263932, reduction = "umap", raster = F, group.by = "orig.ident")
```


```{r}
DimPlot(B_GSE263932, reduction = "umap", raster = F, group.by = "orig.ident")
rm(B_GSE263932)
```


```{r, fig.height= 30, fig.width= 12}
FeaturePlot(GSE263932, features = LSP1_gene_sub, ncol = 3)
```

```{r, fig.height= 9, fig.width= 12}
# T_marker <- c("CD4", "CD8A", "CD69", "CD70", "CD80", "CD154", "CD279", "CD366")
T_marker <- c("CD4", "CD8A", "CD69", "CD70", "CD80", "CD40LG", "PDCD1", "HAVCR2")
DefaultAssay(GSE263932)
is.element(T_marker, rownames(GSE263932))
FeaturePlot(GSE263932, features = T_marker, ncol = 3)
```

```{r, fig.height= 6, fig.width= 12}
B_marker <- c("CD19", "CD79A", "CD79B", "MS4A1", "CD27")

FeaturePlot(GSE263932, features = B_marker, ncol = 3)
```


```{r, fig.width= 8, fig.height= 6}
# B_marker_1 <- c("CD19", "MS4A1", "CR2", "CD22", "CD24", "CD27", "CD38", "IGHD", "PAX5")
B_marker_1 <- c("CD24", "CD38", "IGHD")

FeaturePlot(GSE263932, features = B_marker_1, ncol = 2)

```

```{r, fig.width= 12, fig.height= 12}
# B_marker_2 <- c("BLNK", "BCR", "CXCR5", "CD79A", "CD79B", "IRF4", "SLAMF1", "TNFRSF13B", "FOXP1", "IKZF1", "TCF3", "EBF1", "PRDM1", "BACH2", "ZBTB20", "NFIB")
B_marker_2 <- c("BLNK", "BCR", "CXCR5", "IRF4", "SLAMF1", "TNFRSF13B", "FOXP1", "IKZF1", "TCF3", "EBF1", "PRDM1", "BACH2", "ZBTB20", "NFIB")
FeaturePlot(GSE263932, features = B_marker_2, ncol = 3)
```


```{r}
MCP_counter <-read.table(file = paste0(path, "MCP_counter_marker_genes.txt"), header = T)
C_list <- unique(MCP_counter$Cell.population)
C_list
```

```{r, fig.width= 12, fig.height= 12}
i <- 1
tm <- MCP_counter$HUGO.symbols[is.element(MCP_counter$Cell.population,C_list[i])]
FeaturePlot(GSE263932, features = tm, raster = F, ncol = 3)
i <- 2
tm <- MCP_counter$HUGO.symbols[is.element(MCP_counter$Cell.population,C_list[i])]
FeaturePlot(GSE263932, features = tm, raster = F, ncol = 3)
i <- 3
tm <- MCP_counter$HUGO.symbols[is.element(MCP_counter$Cell.population,C_list[i])]
FeaturePlot(GSE263932, features = tm, raster = F, ncol = 3)
i <- 4
tm <- MCP_counter$HUGO.symbols[is.element(MCP_counter$Cell.population,C_list[i])]
FeaturePlot(GSE263932, features = tm, raster = F, ncol = 3)
i <- 5
tm <- MCP_counter$HUGO.symbols[is.element(MCP_counter$Cell.population,C_list[i])]
FeaturePlot(GSE263932, features = tm, raster = F, ncol = 3)
i <- 6
tm <- MCP_counter$HUGO.symbols[is.element(MCP_counter$Cell.population,C_list[i])]
FeaturePlot(GSE263932, features = tm, raster = F, ncol = 3)
i <- 7
tm <- MCP_counter$HUGO.symbols[is.element(MCP_counter$Cell.population,C_list[i])]
FeaturePlot(GSE263932, features = tm, raster = F, ncol = 3)
i <- 8
tm <- MCP_counter$HUGO.symbols[is.element(MCP_counter$Cell.population,C_list[i])]
FeaturePlot(GSE263932, features = tm, raster = F, ncol = 3)
i <- 9
tm <- MCP_counter$HUGO.symbols[is.element(MCP_counter$Cell.population,C_list[i])]
FeaturePlot(GSE263932, features = tm, raster = F, ncol = 3)
i <- 10
tm <- MCP_counter$HUGO.symbols[is.element(MCP_counter$Cell.population,C_list[i])]
FeaturePlot(GSE263932, features = tm, raster = F, ncol = 3)
```



```{r}
source("~/projects/MK_Rcode/setZ.R")
GSE263932[["LSP1_score"]] <- setZ(LSP1_gene_sub,rownames(GSE263932@assays$RNA$scale.data),GSE263932@assays$RNA$scale.data)
```

```{r}
FeaturePlot(GSE263932, features = "LSP1_score", raster = F)
```

```{r}
DimPlot(GSE263932, raster = F, reduction = "umap")
```


```{r}
GSE263932 <- FindClusters(GSE263932, resolution = 0.3)
DimPlot(GSE263932, raster = F)
```

# ABC signature genes
```{r}
ABC_marker_1 <- c("CD19", "CD80", "CD86", "FAS", "FCRLA", "FCRLB", "FGL2", "CXCL10", "CXCR3", "NKG7", "ITGAM", "ITGB2", "TBX21", "ZBTB32", "FCER2", "CR2")
is.element(ABC_marker_1,rownames(GSE263932))
```

```{r, fig.height= 16, fig.width= 12}
FeaturePlot(GSE263932, features = ABC_marker_1, ncol = 3)
```

```{r}
source("~/projects/MK_Rcode/setZ.R")
GSE263932[["ABC_score"]] <- setZ(ABC_marker_1,rownames(GSE263932@assays$RNA$scale.data),GSE263932@assays$RNA$scale.data)
```

```{r}
FeaturePlot(GSE263932, features = "ABC_score")
GSE263932$ABC_score_pos <- GSE263932$ABC_score>0
DimPlot(GSE263932, group.by = "ABC_score_pos")
```



```{r, fig.height= 8, fig.width= 12}
ABC_marker_2 <- c("EGR1", "NR4A1", "FOSB", "BCL2A1", "CD83", "KLF10", "LGALS1")
is.element(ABC_marker_2, rownames(GSE263932))
FeaturePlot(GSE263932, features = ABC_marker_2, ncol = 3)
```

```{r, fig.height= 12, fig.width= 12}
ABC_marker_3 <- c("CD27", "CRIP1", "CD1C", "CD24", "ACTG1", "HCK", "CD79B", "ANXA2", "TAGLN2", "PTPN22")
is.element(ABC_marker_3, rownames(GSE263932))
FeaturePlot(GSE263932, features = ABC_marker_3, ncol = 3)
```


```{r, fig.height= 12, fig.width= 12}
ABC_marker_4 <- c("RHOB", "LITAF", "FGR", "TNFRSF1B", "FCRL5", "ITGAX", "ZEB2", "FCRL3", "NR4A2", "IDS", "NR4A3")
is.element(ABC_marker_4, rownames(GSE263932))
FeaturePlot(GSE263932, features = ABC_marker_4, ncol = 3)
```


```{r}
if (!file.exists(paste0(path,"markers.rds"))) {
  markers <- FindAllMarkers(GSE263932, min.pct = 0.1, test.use = "LR", logfc.threshold = 0.25)
  saveRDS(markers, file = paste0(path, "markers.rds"))
}
if (!exists("markers")) {
  markers <- readRDS(paste0(path, "markers.rds"))
}
```

```{r}
for (i in 0:15) {
  if (!file.exists(paste0(path,"markers_mast.", i, ".rds"))) {
    eval(parse(text = paste0("markers_mast.", i, " <- FindMarkers(GSE263932, ident.1 = ", i, ", test.use = 'MAST', min.pct = 0.1, logfc.threshold = 0.25, only.pos = T)")))
    eval(parse(text = paste0("saveRDS(markers_mast.", i, ", file = '", path,"markers_mast.",i, ".rds')")))
  }
}

for (i in 0:15) {
  if (!exists(paste0("markers_mast.", i))) {
    eval(parse(text = paste0("markers_mast.", i, " <- readRDS('", path,'markers_mast.', i, ".rds')")))
  }
}

```

```{r, fig.height= 8, fig.width= 16}
markers %>%
  group_by(cluster) %>%
  filter(avg_log2FC > 1) %>%
  slice_head(n = 5) %>%
  ungroup() -> top5

DotPlot(GSE263932, features = top5$gene[!duplicated(top5$gene)] ) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5)) +
  scale_color_gradient2(low = "blue", mid = "white", high = "red", midpoint = 0)
```


```{r}
markers_mast.0 %>% filter(avg_log2FC >1) %>% slice_head(n=5) -> top5_mast
for (i in 1:15) {
  eval(parse(text = paste0("markers_mast.", i, " %>% filter(avg_log2FC >1) %>% slice_head(n=5) -> tm")))
  top5_mast <- rbind(top5_mast, tm)
}
```


```{r, fig.height= 6, fig.width= 16}
DotPlot(GSE263932, features = rownames(top5_mast)[!duplicated(rownames(top5_mast))] ) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5)) +
  scale_color_gradient2(low = "blue", mid = "white", high = "red", midpoint = 0)
```

```{r, fig.height= 60, fig.width= 12}
FeaturePlot(GSE263932, features = rownames(top5_mast), ncol = 3)
```

```{r}
VlnPlot(GSE263932, features = "LSP1_score", pt.size = 0.1)
VlnPlot(GSE263932, features = "LSP1_score", pt.size = 0)
```

```{r}
FeaturePlot(GSE263932, features = "LSP1_score") + 
  scale_color_gradient2(low = "white", mid = "white", high = "blue", midpoint = 0)
GSE263932$LSP1_score_pos <- GSE263932$LSP1_score > 0
DimPlot(GSE263932, group.by = "LSP1_score_pos")
```


```{r}
FeaturePlot(GSE263932, features = "ABC_score")
FeaturePlot(GSE263932, features = "ABC_score") + 
  scale_color_gradient2(low = "white", mid = "white", high = "blue", midpoint = 0)
GSE263932$ABC_score_pos <- GSE263932$ABC_score > 0
DimPlot(GSE263932, group.by = "ABC_score_pos")
```

```{r}
Idents(GSE263932) <- GSE263932$LSP1_score_pos
LSP1_vs_others.marker <- FindMarkers(GSE263932, ident.1 = "TRUE", ident.2 = "FALSE", min.pct = 0.1, logfc.threshold = 0.1, test.use = "MAST")

Idents(GSE263932) <- GSE263932$ABC_score_pos
ABC_vs_others.marker <- FindMarkers(GSE263932, ident.1 = "TRUE", ident.2 = "FALSE", min.pct = 0.1, logfc.threshold = 0.1, test.use = "MAST")
```

```{r}
temp <- colnames(GSE263932)[GSE263932$LSP1_score_pos == "TRUE" & GSE263932$ABC_score_pos == "TRUE"]
Idents(GSE263932, cells = temp) <- "Double positive"
temp <- colnames(GSE263932)[GSE263932$LSP1_score_pos == "FALSE" & GSE263932$ABC_score_pos == "TRUE"]
Idents(GSE263932, cells = temp) <- "ABC positive"
temp <- colnames(GSE263932)[GSE263932$LSP1_score_pos == "TRUE" & GSE263932$ABC_score_pos == "FALSE"]
Idents(GSE263932, cells = temp) <- "LSP1 positive"
temp <- colnames(GSE263932)[GSE263932$LSP1_score_pos == "FALSE" & GSE263932$ABC_score_pos == "FALSE"]
Idents(GSE263932, cells = temp) <- "Double negative"
Idents(GSE263932) <- factor(Idents(GSE263932), levels = c("LSP1 positive", "ABC positive", "Double positive", "Double negative"))
GSE263932$anno_ABC_LSP1 <- Idents(GSE263932)
```

```{r}
Idents(GSE263932) <- GSE263932$anno_ABC_LSP1
DimPlot(GSE263932)
```


```{r}
All_markers <- FindAllMarkers(GSE263932, min.pct = 0.1, logfc.threshold = 0.1, test.use = "MAST")
```

```{r}
if (!file.exists(paste0(path,"GSE263932_020425.rds"))) {
  saveRDS(GSE263932, file = paste0(path,"GSE263932_020425.rds"))
}
if (!exists("GSE263932")) {
  GSE263932 <- readRDS(paste0(path,"GSE263932_020425.rds"))
}
```

```{r}
if (file.exists(paste0(path,"LSP1_vs_others_022025.rds"))) {
  saveRDS(LSP1_vs_others.marker, file = paste0(path,"LSP1_vs_others_022025.rds"))
  saveRDS(ABC_vs_others.marker, file = paste0(path,"ABC_vs_others_022025.rds"))
  saveRDS(All_markers, file = paste0(path,"All_markers_022025.rds"))
}
```


```{r}
if (!file.exists(paste0(path,"GSE263932_meta.rds"))) {
  saveRDS(GSE263932@meta.data, file = paste0(path,"GSE263932_meta.rds"))
}
```



```{r}
source("~/projects/MK_Rcode/volcano_scdata.R")
vol1 <- volcano_scdata(LSP1_vs_others.marker,"LSP1 pos vs others")
vol2 <- volcano_scdata(ABC_vs_others.marker,"ABC pos vs others")
```

```{r}
library(clusterProfiler)
library(enrichplot)
library(msigdbr)
library(stringr)
set.seed(2024)
hallmark_geneset <- msigdbr(species = "Homo sapiens",  category = "H")
hallmark_geneset$gs_name_short <- str_extract(hallmark_geneset$gs_name, "(?<=HALLMARK_).*$")
head(hallmark_geneset)
```

# LSP1 vs others
```{r}
sort_glist <- LSP1_vs_others.marker$avg_log2FC
names(sort_glist) <- rownames(LSP1_vs_others.marker)
sort_glist <- sort(sort_glist, decreasing = T)
gsea_result.LSP1 <- GSEA(geneList = sort_glist, TERM2GENE = select(hallmark_geneset, gs_name_short, gene_symbol), seed = T)
dotplot(gsea_result.LSP1, showCategory=10, split=".sign") + facet_grid(.~.sign)
```

# ABC vs others
```{r}
sort_glist <- ABC_vs_others.marker$avg_log2FC
names(sort_glist) <- rownames(ABC_vs_others.marker)
sort_glist <- sort(sort_glist, decreasing = T)
gsea_result.ABS <- GSEA(geneList = sort_glist, TERM2GENE = select(hallmark_geneset, gs_name_short, gene_symbol), seed = T)
dotplot(gsea_result.ABS, showCategory=10, split=".sign") + facet_grid(.~.sign)
```


```{r}
DimPlot(GSE263932)
```

```{r, fig.height= 4, fig.width= 8}
All_markers %>%
  group_by(cluster) %>%
  filter(avg_log2FC > 0) %>%
  filter(p_val_adj < 0.05) %>%
  arrange(desc(avg_log2FC)) %>%
  slice_head(n = 5) %>%
  ungroup() -> top5

DotPlot(GSE263932, features = top5$gene[c(6:20,1:5)] ) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5)) +
  scale_color_gradient2(low = "blue", mid = "white", high = "red", midpoint = 0)
```

```{r}
All_markers %>%
  filter(cluster == "LSP1 positive") -> temp
vol3 <- volcano_scdata(temp,"LSP1 pos vs others")
All_markers %>%
  filter(cluster == "ABC positive") -> temp
vol4 <- volcano_scdata(temp,"ABC pos vs others")
All_markers %>%
  filter(cluster == "Double negative") -> temp
vol5 <- volcano_scdata(temp,"Double negative vs others")
All_markers %>%
  filter(cluster == "Double positive") -> temp
vol6 <- volcano_scdata(temp,"Double positive vs others")
```


```{r}
LSP1_vs_ABC.marker <- FindMarkers(GSE263932, ident.1 = "LSP1 positive", ident.2 = "ABC positive", min.pct = 0.1, logfc.threshold = 0.1, test.use = "MAST")
DoubleP_vs_others.marker <- FindMarkers(GSE263932, ident.1 = "Double positive", min.pct = 0.1, logfc.threshold = 0.1, test.use = "MAST")
```

```{r}
vol7 <- volcano_scdata(LSP1_vs_ABC.marker, "LSP1 vs ABC")
vol8 <- volcano_scdata(DoubleP_vs_others.marker, "Double positive vs others")
```
# LSP1 vs ABC 
```{r}
sort_glist <- LSP1_vs_ABC.marker$avg_log2FC
names(sort_glist) <- rownames(LSP1_vs_ABC.marker)
sort_glist <- sort(sort_glist, decreasing = T)
gsea_result.LSP1vsABS <- GSEA(geneList = sort_glist, TERM2GENE = select(hallmark_geneset, gs_name_short, gene_symbol), seed = T, pvalueCutoff = 0.99)
aa <- dotplot(gsea_result.LSP1vsABS, showCategory=10, split=".sign") + facet_grid(.~.sign)
aa
saveRDS(gsea_result.LSP1vsABS, file = paste0(path,"gsea_GSE263932.rds"))
```


# Double Positive vs others
```{r}
sort_glist <- DoubleP_vs_others.marker$avg_log2FC
names(sort_glist) <- rownames(DoubleP_vs_others.marker)
sort_glist <- sort(sort_glist, decreasing = T)
gsea_result.DoubleP_vs_others <- GSEA(geneList = sort_glist, TERM2GENE = select(hallmark_geneset, gs_name_short, gene_symbol), seed = T)
dotplot(gsea_result.DoubleP_vs_others, showCategory=10, split=".sign") + facet_grid(.~.sign)
```







